version: '3.4'

services:
  # webapp:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: base
  catalogdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catalogdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data

volumes:
  postgres_catalog: